{
  "default": true,
  # Ignore line length in code blocks
  "MD013": { "code_blocks": false},
  # Allow sub-headings in different sections to have the same name
  "MD024": {"allow_different_nesting": true},
  # Allow raw HTML - the power is yours
  "MD033": false,
}
