repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-toml
      - id: check-merge-conflict
      - id: check-yaml
      - id: mixed-line-ending
      - id: requirements-txt-fixer
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        # W503/504: Line break before binary operator; black formats this way
        # E203: Whitespace before ":" while slicing; black formats this way
        # Line length: match the black default of 88
        args: ['--max-line-length=88', '--ignore=W504, W503, E203']
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.30.0
    hooks:
      - id: markdownlint-fix
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v13.0.0
    hooks:
      - id: clang-format
